-- ============================================================
-- SamaCommande / GesCommande — Schéma Supabase
-- À copier-coller dans : Supabase > SQL Editor > New Query
-- ============================================================

-- ──────────────────────────────────────────────────────────────
-- 1. TABLE : orders
-- ──────────────────────────────────────────────────────────────
CREATE TABLE orders (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  client     VARCHAR(255) NOT NULL,
  phone      VARCHAR(30) DEFAULT '',
  email      VARCHAR(255) DEFAULT '',
  address    VARCHAR(255) DEFAULT '',
  payment    VARCHAR(50) NOT NULL,
  status     VARCHAR(50) NOT NULL DEFAULT 'pending',
  notes      TEXT DEFAULT '',
  date       DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────
-- 2. TABLE : order_items
-- ──────────────────────────────────────────────────────────────
CREATE TABLE order_items (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  name       VARCHAR(255) NOT NULL,
  qty        INTEGER NOT NULL DEFAULT 1,
  price      DECIMAL(12, 2) NOT NULL DEFAULT 0,
  position   INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ──────────────────────────────────────────────────────────────
-- 3. INDEX pour la performance
-- ──────────────────────────────────────────────────────────────
CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_date    ON orders(date DESC);
CREATE INDEX idx_orders_status  ON orders(status);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);

-- ──────────────────────────────────────────────────────────────
-- 4. Mise à jour automatique de updated_at
-- ──────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- ──────────────────────────────────────────────────────────────
-- 5. Row Level Security (RLS)
--    Chaque utilisateur ne voit que SES commandes
-- ──────────────────────────────────────────────────────────────

-- Activer RLS sur les deux tables
ALTER TABLE orders      ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- ── Policies pour orders ──

CREATE POLICY "Utilisateur voit ses commandes"
  ON orders FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Utilisateur crée ses commandes"
  ON orders FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Utilisateur modifie ses commandes"
  ON orders FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Utilisateur supprime ses commandes"
  ON orders FOR DELETE
  USING (auth.uid() = user_id);

-- ── Policies pour order_items ──
-- Un utilisateur peut gérer les items de SES commandes uniquement

CREATE POLICY "Utilisateur voit ses articles"
  ON order_items FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM orders
      WHERE orders.id = order_items.order_id
        AND orders.user_id = auth.uid()
    )
  );

CREATE POLICY "Utilisateur crée ses articles"
  ON order_items FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM orders
      WHERE orders.id = order_items.order_id
        AND orders.user_id = auth.uid()
    )
  );

CREATE POLICY "Utilisateur modifie ses articles"
  ON order_items FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM orders
      WHERE orders.id = order_items.order_id
        AND orders.user_id = auth.uid()
    )
  );

CREATE POLICY "Utilisateur supprime ses articles"
  ON order_items FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM orders
      WHERE orders.id = order_items.order_id
        AND orders.user_id = auth.uid()
    )
  );

-- ──────────────────────────────────────────────────────────────
-- 6. Activer Realtime (optionnel, pour les mises à jour en temps réel)
-- ──────────────────────────────────────────────────────────────
ALTER PUBLICATION supabase_realtime ADD TABLE orders;
ALTER PUBLICATION supabase_realtime ADD TABLE order_items;
