export const PLANS = {
  starter: {
    id: "starter",
    name: "Starter",
    price: 0,
    priceLabel: "Gratuit",
    description: "Pour démarrer et gérer vos premières commandes",
    limits: {
      maxOrders: 30,
      maxItemsPerOrder: 10,
      hasAI: false,
      hasInvoice: false,
      hasCharts: true,
      hasExport: false,
      hasWhatsApp: false,
    },
    features: [
      { label: "Jusqu'à 30 commandes par mois", included: true },
      { label: "10 articles max par commande", included: true },
      { label: "KPIs du tableau de bord", included: true },
      { label: "Recherche et filtres", included: true },
      { label: "Graphiques basiques", included: true, isNew: true },
      { label: "Envoi WhatsApp automatique", included: false },
      { label: "Assistant IA", included: false },
      { label: "Génération de factures PDF", included: false },
      { label: "Export CSV des commandes", included: false },
      { label: "Support communauté", included: true, isSupport: true },
    ],
  },
  pro: {
    id: "pro",
    name: "Pro",
    price: 5000,
    priceLabel: "5 000 F CFA",
    period: "/ mois",
    description: "Pour les pros qui veulent booster leur business avec l'IA",
    badge: "Populaire",
    limits: {
      maxOrders: Infinity,
      maxItemsPerOrder: Infinity,
      hasAI: true,
      hasInvoice: true,
      hasCharts: true,
      hasExport: true,
      hasWhatsApp: true,
    },
    features: [
      { label: "Commandes illimitées", included: true },
      { label: "Articles illimités par commande", included: true },
      { label: "KPIs du tableau de bord", included: true },
      { label: "Recherche et filtres", included: true },
      { label: "Graphiques et analytics avancés", included: true },
      { label: "Envoi WhatsApp automatique", included: true },
      { label: "Assistant IA — 5 analyses/jour", included: true, highlight: true },
      { label: "Génération de factures PDF", included: true },
      { label: "Export CSV des commandes", included: true },
      { label: "Support prioritaire", included: true, isSupport: true },
    ],
  },
};
